pragma Singleton

import QtQuick
import Quickshell
import Quickshell.Io
import qs.services

// Colors generated by matugen from the wallpaper. Reloads live when the file changes.
Singleton {
    id: root

    // Written by the quickshell template in ~/.config/matugen/config.toml
    readonly property string colorsPath: `${Quickshell.env("HOME")}/.local/state/quickshell/colors.json`

    property string wallpaper: ""

    // Fallback palette until colors.json loads. Names are matugen's keys in camelCase, except
    // "on_x" becomes "xText" (QML treats names starting with "on" as signal handlers)
    // and "error" becomes "critical".
    property color surface: "#111318"
    property color surfaceContainer: "#1d2024"
    property color surfaceContainerHigh: "#272a2f"
    property color surfaceContainerHighest: "#32353a"
    property color surfaceText: "#e1e2e8"
    property color surfaceVariantText: "#c3c6cf"
    property color outline: "#8d9199"
    property color outlineVariant: "#43474e"
    property color primary: "#a4c9fe"
    property color primaryText: "#00315c"
    property color primaryContainer: "#1f4876"
    property color primaryContainerText: "#d3e3ff"
    property color secondary: "#bcc7db"
    property color secondaryContainer: "#3c4758"
    property color secondaryContainerText: "#d8e3f8"
    property color tertiary: "#d9bde3"
    property color tertiaryContainer: "#543f5e"
    property color tertiaryContainerText: "#f5d9ff"
    property color critical: "#ffb4ab"
    property color errorContainer: "#93000a"
    property color errorContainerText: "#ffdad6"

    // Glass: how see-through surfaces are. 0.4 matches the old waybar.
    readonly property real glassOpacity: Settings.data.glassOpacity
    readonly property color glass: Qt.alpha(surface, glassOpacity)
    readonly property color glassHover: Qt.alpha(surfaceContainerHighest, glassOpacity + 0.2)
    // Faint 1px edge that makes glass read as glass
    readonly property color glassEdge: Qt.alpha(surfaceText, 0.08)
    // Tinted fills for buttons and chips: wallpaper colors, still see-through
    readonly property color tonal: Qt.alpha(secondaryContainer, 0.55)
    readonly property color accent: Qt.alpha(primaryContainer, 0.8)
    readonly property color accentSoft: Qt.alpha(tertiaryContainer, 0.75)
    readonly property color danger: Qt.alpha(errorContainer, 0.8)

    // Canvas needs CSS color strings
    function css(c: color): string {
        return `rgba(${Math.round(c.r * 255)},${Math.round(c.g * 255)},${Math.round(c.b * 255)},${c.a})`;
    }
    // Popouts sit over windows, not just wallpaper, so they need more contrast
    readonly property color panel: Qt.alpha(surface, 0.8)
    readonly property color textDim: Qt.alpha(surfaceText, 0.4)

    function apply(json: string): void {
        const data = JSON.parse(json);
        for (const [key, value] of Object.entries(data)) {
            if (key === "image") {
                wallpaper = value;
                continue;
            }
            const renamed = key === "error" ? "critical" : key.replace(/^on_(.+)$/, "$1_text");
            const name = renamed.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
            if (typeof value === "string" && value.startsWith("#") && root.hasOwnProperty(name))
                root[name] = value;
        }
    }

    FileView {
        path: root.colorsPath
        watchChanges: true
        onFileChanged: reload()
        onLoaded: {
            try {
                root.apply(text());
            } catch (e) {
                // matugen can be mid-write; the next change event reloads it
                console.warn(`Theme: could not read ${root.colorsPath}: ${e}`);
            }
        }
    }
}
